services:
  - type: web
    name: builder-neon-lab
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: OPENAI_API_KEY
        value: demo_openai_key_12345
      - key: STRIPE_SECRET_KEY
        value: sk_test_demo_stripe_key_12345
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_demo_stripe_key_12345
      - key: CORS_ORIGIN
        value: https://builder-neon-lab.onrender.com 